name: Publish blog
on:
    push:
        branchs: [ master ]
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Install packages
              run: |
                sudo apt-get update -qq
                sudo apt-get install graphviz -qq
            - name: Checkout blog source
              uses: actions/checkout@v2
              with:
                path: blog
            - name: Checkout Pelican Plugins
              uses: actions/checkout@v2
              with:
                repository: getpelican/pelican-plugins
                path: pelican-plugins
            - name: Set up Python 3.x
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'
                architecture: 'x64'
            - name: Install dependencies
              working-directory: blog
              run: |
                python -m pip install --upgrade pip
                python -m pip install pelican markdown
                python -m pip install -r requirements.txt
            - name: Compile HTML
              working-directory: blog
              run: |
                make html

